<?php 

// Each new term in the Fibonacci sequence is generated by adding the previous two terms.
// By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

require_once(dirname(__FILE__) . '/../bootstrap.php');
ini_set('memory_limit', '-1');

$sum = 2;
$prev2 = 1;
$prev1 = 2;
for (; ($prev1 + $prev2) < 4000000;) {
    $curr = $prev1 + $prev2;
    $prev2 = $prev1;
    $prev1 = $curr;
    if($curr %2 == 0) {
        $sum += $curr;
    }
}

echo "\nsum: $sum\n";